name: Log

options:
  bundleIdPrefix: dev.jano.log
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 16.2

settings:
    DEVELOPMENT_TEAM: V45TPHNJ4Q

targets:

  Log:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - LogTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 16.2
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.log
       PRODUCT_NAME: Log
    sources: 
       - sources/main
    type: framework

  LogTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 16.2
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.log.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: Log
